# Generated by Django 5.0.2 on 2024-02-26 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('cooking_steps', models.CharField(max_length=250)),
                ('cooking_time', models.IntegerField(default=30)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('author', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSiteRecipe.recipe')),
                ('id_recipe_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSiteRecipe.recipecategories')),
            ],
        ),
    ]
